/*
 * Copyright (c) 2025 mr258876
 * SPDX-License-Identifier: MIT
 */

#include <stdint.h>

#include "rl_usb.h"

#include "HostCommWarpper.h"
#include "Fancontrol.h"

// HID Usage Tables: 1.6.0
// Descriptor size: 388 (bytes)
// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)
// +----------+---------+-------------------+
// | ReportId | Kind    | ReportSizeInBytes |
// +----------+---------+-------------------+
// |        1 | Feature |                15 |
// +----------+---------+-------------------+
// |        2 | Feature |                18 |
// +----------+---------+-------------------+
// |        3 | Feature |                18 |
// +----------+---------+-------------------+
// |        4 | Feature |                18 |
// +----------+---------+-------------------+
// |        5 | Feature |                 4 |
// +----------+---------+-------------------+
// |        6 | Feature |                19 |
// +----------+---------+-------------------+
// |        7 | Feature |                 5 |
// +----------+---------+-------------------+
// |        8 | Feature |                 6 |
// +----------+---------+-------------------+
// |        9 | Feature |                 6 |
// +----------+---------+-------------------+
const uint8_t usbd_hid0_report_descriptor[] =
    {
        0x06, 0x60, 0xFF,             // UsagePage(USBreezeUsagePage[0xFF60])
        0x09, 0x01,                   // UsageId(USBreezeController[0x0001])
        0xA1, 0x01,                   // Collection(Application)
        0x85, 0x01,                   //     ReportId(1)
        0x09, 0x10,                   //     UsageId(FanInfoReport[0x0010])
        0xA1, 0x02,                   //     Collection(Logical)
        0x09, 0x11,                   //         UsageId(DeviceFwBcd[0x0011])
        0x15, 0x00,                   //         LogicalMinimum(0)
        0x27, 0xFF, 0xFF, 0x00, 0x00, //         LogicalMaximum(65,535)
        0x95, 0x01,                   //         ReportCount(1)
        0x75, 0x10,                   //         ReportSize(16)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0x12,                   //         UsageId(DeviceSerial[0x0012])
        0x27, 0xFF, 0xFF, 0xFF, 0x7F, //         LogicalMaximum(2,147,483,647)
        0x75, 0x20,                   //         ReportSize(32)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0x13,                   //         UsageId(FanCount[0x0013])
        0x09, 0x14,                   //         UsageId(FanCapabilities[0x0014])
        0x26, 0xFF, 0x00,             //         LogicalMaximum(255)
        0x95, 0x02,                   //         ReportCount(2)
        0x75, 0x08,                   //         ReportSize(8)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0x15,                   //         UsageId(FanPwmMaxPercent[0x0015])
        0x27, 0xFF, 0xFF, 0x00, 0x00, //         LogicalMaximum(65,535)
        0x95, 0x01,                   //         ReportCount(1)
        0x75, 0x10,                   //         ReportSize(16)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0x16,                   //         UsageId(TempSensorCount[0x0016])
        0x09, 0x17,                   //         UsageId(TempSensorCapabilities[0x0017])
        0x09, 0x18,                   //         UsageId(FanCurvePointsMax[0x0018])
        0x26, 0xFF, 0x00,             //         LogicalMaximum(255)
        0x95, 0x03,                   //         ReportCount(3)
        0x75, 0x08,                   //         ReportSize(8)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0x19,                   //         UsageId(FanRpmPollMinMs[0x0019])
        0x27, 0xFF, 0xFF, 0x00, 0x00, //         LogicalMaximum(65,535)
        0x95, 0x01,                   //         ReportCount(1)
        0x75, 0x10,                   //         ReportSize(16)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0xC0,                         //     EndCollection()
        0x85, 0x02,                   //     ReportId(2)
        0x09, 0x20,                   //     UsageId(FanRpmReport[0x0020])
        0xA1, 0x02,                   //     Collection(Logical)
        0x09, 0x21,                   //         UsageId(FanRpmIdOffset[0x0021])
        0x26, 0xFF, 0x00,             //         LogicalMaximum(255)
        0x75, 0x08,                   //         ReportSize(8)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0x22,                   //         UsageId(FanRpmsInPacket[0x0022])
        0x25, 0x04,                   //         LogicalMaximum(4)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0x23,                   //         UsageId(FanRpmValue[0x0023])
        0x27, 0xFF, 0xFF, 0xFF, 0x7F, //         LogicalMaximum(2,147,483,647)
        0x95, 0x04,                   //         ReportCount(4)
        0x75, 0x20,                   //         ReportSize(32)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0xC0,                         //     EndCollection()
        0x85, 0x03,                   //     ReportId(3)
        0x09, 0x30,                   //     UsageId(TempSensorReport[0x0030])
        0xA1, 0x02,                   //     Collection(Logical)
        0x09, 0x31,                   //         UsageId(TempSensorIdOffset[0x0031])
        0x26, 0xFF, 0x00,             //         LogicalMaximum(255)
        0x95, 0x01,                   //         ReportCount(1)
        0x75, 0x08,                   //         ReportSize(8)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0x32,                   //         UsageId(TempSensorsInPacket[0x0032])
        0x25, 0x08,                   //         LogicalMaximum(8)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0x33,                   //         UsageId(TempSensorValue[0x0033])
        0x16, 0x00, 0x80,             //         LogicalMinimum(-32,768)
        0x26, 0xFF, 0x7F,             //         LogicalMaximum(32,767)
        0x95, 0x08,                   //         ReportCount(8)
        0x75, 0x10,                   //         ReportSize(16)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0xC0,                         //     EndCollection()
        0x85, 0x04,                   //     ReportId(4)
        0x09, 0x40,                   //     UsageId(FanControlValueReport[0x0040])
        0xA1, 0x02,                   //     Collection(Logical)
        0x09, 0x41,                   //         UsageId(FanControlIdOffset[0x0041])
        0x15, 0x00,                   //         LogicalMinimum(0)
        0x26, 0xFF, 0x00,             //         LogicalMaximum(255)
        0x95, 0x01,                   //         ReportCount(1)
        0x75, 0x08,                   //         ReportSize(8)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0x42,                   //         UsageId(FanControlsInPacket[0x0042])
        0x25, 0x08,                   //         LogicalMaximum(8)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0x43,                   //         UsageId(FanControlValue[0x0043])
        0x16, 0x00, 0x80,             //         LogicalMinimum(-32,768)
        0x26, 0xFF, 0x7F,             //         LogicalMaximum(32,767)
        0x95, 0x08,                   //         ReportCount(8)
        0x75, 0x10,                   //         ReportSize(16)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0xC0,                         //     EndCollection()
        0x85, 0x05,                   //     ReportId(5)
        0x09, 0x50,                   //     UsageId(FanCurveCfgReport[0x0050])
        0xA1, 0x02,                   //     Collection(Logical)
        0x09, 0x1A,                   //         UsageId(FanId[0x001A])
        0x09, 0x51,                   //         UsageId(OpFlags[0x0051])
        0x09, 0x52,                   //         UsageId(CurvePointCountTotal[0x0052])
        0x09, 0x1B,                   //         UsageId(TempSensorId[0x001B])
        0x15, 0x00,                   //         LogicalMinimum(0)
        0x26, 0xFF, 0x00,             //         LogicalMaximum(255)
        0x95, 0x04,                   //         ReportCount(4)
        0x75, 0x08,                   //         ReportSize(8)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0xC0,                         //     EndCollection()
        0x85, 0x06,                   //     ReportId(6)
        0x09, 0x60,                   //     UsageId(FanCurvePointsReport[0x0060])
        0xA1, 0x02,                   //     Collection(Logical)
        0x09, 0x1A,                   //         UsageId(FanId[0x001A])
        0x09, 0x61,                   //         UsageId(CurvePointIdOffset[0x0061])
        0x95, 0x02,                   //         ReportCount(2)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0x62,                   //         UsageId(CurvePointsInPacket[0x0062])
        0x25, 0x04,                   //         LogicalMaximum(4)
        0x95, 0x01,                   //         ReportCount(1)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0x63,                   //         UsageId(CurvePointTemp[0x0063])
        0x09, 0x64,                   //         UsageId(CurvePointPWM[0x0064])
        0x09, 0x63,                   //         UsageId(CurvePointTemp[0x0063])
        0x09, 0x64,                   //         UsageId(CurvePointPWM[0x0064])
        0x09, 0x63,                   //         UsageId(CurvePointTemp[0x0063])
        0x09, 0x64,                   //         UsageId(CurvePointPWM[0x0064])
        0x09, 0x63,                   //         UsageId(CurvePointTemp[0x0063])
        0x09, 0x64,                   //         UsageId(CurvePointPWM[0x0064])
        0x16, 0x00, 0x80,             //         LogicalMinimum(-32,768)
        0x26, 0xFF, 0x7F,             //         LogicalMaximum(32,767)
        0x95, 0x08,                   //         ReportCount(8)
        0x75, 0x10,                   //         ReportSize(16)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0xC0,                         //     EndCollection()
        0x85, 0x07,                   //     ReportId(7)
        0x09, 0xE0,                   //     UsageId(RgbInfoReport[0x00E0])
        0xA1, 0x02,                   //     Collection(Logical)
        0x09, 0xE1,                   //         UsageId(RgbHidChannelCount[0x00E1])
        0x09, 0xE2,                   //         UsageId(RgbPhyChannelCount[0x00E2])
        0x15, 0x00,                   //         LogicalMinimum(0)
        0x26, 0xFF, 0x00,             //         LogicalMaximum(255)
        0x95, 0x02,                   //         ReportCount(2)
        0x75, 0x08,                   //         ReportSize(8)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0xE3,                   //         UsageId(RgbLedCapacity[0x00E3])
        0x27, 0xFF, 0xFF, 0x00, 0x00, //         LogicalMaximum(65,535)
        0x95, 0x01,                   //         ReportCount(1)
        0x75, 0x10,                   //         ReportSize(16)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0xE4,                   //         UsageId(RgbDebugDataFormat[0x00E4])
        0x26, 0xFF, 0x00,             //         LogicalMaximum(255)
        0x75, 0x08,                   //         ReportSize(8)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0xC0,                         //     EndCollection()
        0x85, 0x08,                   //     ReportId(8)
        0x09, 0xD0,                   //     UsageId(RgbHidChannelMapReport[0x00D0])
        0xA1, 0x02,                   //     Collection(Logical)
        0x09, 0xD1,                   //         UsageId(RgbHidChannelFlag[0x00D1])
        0x09, 0xE5,                   //         UsageId(RgbHidChannelId[0x00E5])
        0x95, 0x02,                   //         ReportCount(2)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0xD2,                   //         UsageId(RgbHidChannelStartId[0x00D2])
        0x09, 0xD3,                   //         UsageId(RgbHidChannelLedCount[0x00D3])
        0x27, 0xFF, 0xFF, 0x00, 0x00, //         LogicalMaximum(65,535)
        0x75, 0x10,                   //         ReportSize(16)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0xC0,                         //     EndCollection()
        0x85, 0x09,                   //     ReportId(9)
        0x09, 0xC0,                   //     UsageId(RgbPhyChannelMapReport[0x00C0])
        0xA1, 0x02,                   //     Collection(Logical)
        0x09, 0xC1,                   //         UsageId(RgbPhyChannelFlag[0x00C1])
        0x09, 0xE6,                   //         UsageId(RgbPhyChannelId[0x00E6])
        0x26, 0xFF, 0x00,             //         LogicalMaximum(255)
        0x75, 0x08,                   //         ReportSize(8)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0x09, 0xC2,                   //         UsageId(RgbPhyChannelStartId[0x00C2])
        0x09, 0xC3,                   //         UsageId(RgbPhyChannelLedCount[0x00C3])
        0x27, 0xFF, 0xFF, 0x00, 0x00, //         LogicalMaximum(65,535)
        0x75, 0x10,                   //         ReportSize(16)
        0xB1, 0x02,                   //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0xC0,                         //     EndCollection()
        0xC0,                         // EndCollection()
};

// \brief Prepare HID Report data to send.
// \param[in]   rtype   report type:
//                - HID_REPORT_INPUT           = input report requested
//                - HID_REPORT_FEATURE         = feature report requested
// \param[in]   req     request type:
//                - USBD_HID_REQ_EP_CTRL       = control endpoint request
//                - USBD_HID_REQ_PERIOD_UPDATE = idle period expiration request
//                - USBD_HID_REQ_EP_INT        = previously sent report on interrupt endpoint request
// \param[in]   rid     report ID (0 if only one report exists).
// \param[out]  buf     buffer containing report data to send.
// \return              number of report data bytes prepared to send or invalid report requested.
//              - value >= 0: number of report data bytes prepared to send
//              - value = -1: invalid report requested
int32_t USBD_HID0_GetReport(uint8_t rtype, uint8_t req, uint8_t rid, uint8_t *buf)
{

  switch (rtype)
  {
  case HID_REPORT_INPUT:
    return 0;

  case HID_REPORT_FEATURE:
    // The first byte of data is report ID
    buf[0] = rid;
    buf++;

    switch (rid)
    {
    case FAN_INFO_REPORT_ID:
      return Fan_Control_Get_Info_Report(buf);
    case FAN_PWM_REPORT_ID:
      return Fan_Control_Get_RPM_Report(buf);
    case FAN_TEMP_SENSOR_REPORT_ID:
      return Fan_Control_Get_Temp_Report(buf);
    case FAN_HOST_OVERRIDE_REPORT:
      return Fan_Control_Get_Control_Report(buf);
    case FAN_CURVE_CFG_REPORT:
      return Fan_Control_Get_Curve_Cfg_Report(buf);
    case FAN_CURVE_POINTS_REPORT:
      return Fan_Control_Get_Curve_Point_Report(buf);
    case RGB_CONFIG_INFO_REPORT_ID:
      return RGB_Config_Get_Info_Report(buf);
    case RGB_CONFIG_HID_CHANNEL_MAP_REPORT_ID:
      return RGB_Config_Get_Hid_Channel_Map_Report(buf);
    case RGB_CONFIG_PHY_CHANNEL_MAP_REPORT_ID:
      return RGB_Config_Get_Phy_Channel_Map_Report(buf);

    default:
      break;
    }

  default:
    break;
  }

  return -1;
}

// \brief Process received HID Report data.
// \param[in]   rtype   report type:
//                - HID_REPORT_OUTPUT    = output report received
//                - HID_REPORT_FEATURE   = feature report received
// \param[in]   req     request type:
//                - USBD_HID_REQ_EP_CTRL = report received on control endpoint
//                - USBD_HID_REQ_EP_INT  = report received on interrupt endpoint
// \param[in]   rid     report ID (0 if only one report exists).
// \param[in]   buf     buffer that receives report data.
// \param[in]   len     length of received report data.
// \return      true    received report data processed.
// \return      false   received report data not processed or request not supported.
bool USBD_HID0_SetReport(uint8_t rtype, uint8_t req, uint8_t rid, const uint8_t *buf, int32_t len)
{

  switch (rtype)
  {
  case HID_REPORT_OUTPUT:
    return true;

  case HID_REPORT_FEATURE:
    // The first byte of data is report ID
    len--;
    buf++;

    switch (rid)
    {
    case FAN_PWM_REPORT_ID:
      return Fan_Control_Set_RPM_Report(buf, len);
    case FAN_TEMP_SENSOR_REPORT_ID:
      return Fan_Control_Set_Temp_Report(buf, len);
    case FAN_HOST_OVERRIDE_REPORT:
      return Fan_Control_Set_Control_Report(buf, len);
    case FAN_CURVE_CFG_REPORT:
      return Fan_Control_Set_Curve_Cfg_Report(buf, len);
    case FAN_CURVE_POINTS_REPORT:
      return Fan_Control_Set_Curve_Point_Report(buf, len);
    case RGB_CONFIG_HID_CHANNEL_MAP_REPORT_ID:
      return RGB_Config_Set_Hid_Channel_Map_Report(buf, len);
    case RGB_CONFIG_PHY_CHANNEL_MAP_REPORT_ID:
      return RGB_Config_Set_Phy_Channel_Map_Report(buf, len);

    default:
      break;
    }

  default:
    break;
  }

  return false;
}
