/*
 * Copyright (c) 2025 mr258876
 * SPDX-License-Identifier: MIT
 */

#include <stdint.h>

#include "rl_usb.h"

#include "HostCommWarpper.h"
#include "Fancontrol.h"

// HID Usage Tables: 1.6.0
// Descriptor size: 75 (bytes)
// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)
// +----------+---------+-------------------+
// | ReportId | Kind    | ReportSizeInBytes |
// +----------+---------+-------------------+
// |        1 | Input   |                32 |
// +----------+---------+-------------------+
// |        1 | Output  |                32 |
// +----------+---------+-------------------+
// |        1 | Feature |                 8 |
// +----------+---------+-------------------+
// |        2 | Feature |                 2 |
// +----------+---------+-------------------+
const uint8_t usbd_hid0_report_descriptor[] =
    {
        0x05, 0x01,                                           // UsagePage(Generic Desktop[0x0001])
        0x09, 0x0B,                                           // UsageId(Computer Chassis Device[0x000B])
        0xA1, 0x01,                                           // Collection(Application)
        0x85, 0x01,                                           //     ReportId(1)
        0x09, 0xC0,                                           //     UsageId(Sensor Zone[0x00C0])
        0xA1, 0x02,                                           //     Collection(Logical)
        0x09, 0xC1,                                           //         UsageId(RPM[0x00C1])
        0x15, 0x00,                                           //         LogicalMinimum(0)
        0x27, 0xFF, 0xFF, 0xFF, 0x7F,                         //         LogicalMaximum(2,147,483,647)
        0x95, SYSTEM_FAN_COUNT,                               //         ReportCount(8)
        0x75, SYSTEM_FAN_COUNT * sizeof(SYSTEM_FAN_RPM_TYPE), //         ReportSize(32)
        0x81, 0x02,                                           //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
        0xC0,                                                 //     EndCollection()
        0x09, 0xC0,                                           //     UsageId(Sensor Zone[0x00C0])
        0xA1, 0x02,                                           //     Collection(Logical)
        0x09, 0xC1,                                           //         UsageId(RPM[0x00C1])
        0x91, 0x02,                                           //         Output(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0xC0,                                                 //     EndCollection()
        0x06, 0x1C, 0xFF,                                     //     UsagePage(Vendor Usage Page[0xFF1C])
        0x09, 0x01,                                           //     UsageId(Fan Controls[0x0001])
        0xA1, 0x02,                                           //     Collection(Logical)
        0x09, 0x02,                                           //         UsageId(Fan Control Level[0x0002])
        0x25, 0x64,                                           //         LogicalMaximum(100)
        0x75, 0x08,                                           //         ReportSize(8)
        0xB1, 0x02,                                           //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0xC0,                                                 //     EndCollection()
        0x85, 0x02,                                           //     ReportId(2)
        0x09, 0x11,                                           //     UsageId(Sensors[0x0011])
        0xA1, 0x02,                                           //     Collection(Logical)
        0x09, 0x12,                                           //         UsageId(Temp Sensor[0x0012])
        0x16, 0x70, 0xFE,                                     //         LogicalMinimum(-400)
        0x26, 0xB0, 0x04,                                     //         LogicalMaximum(1,200)
        0x95, 0x01,                                           //         ReportCount(1)
        0x75, 0x10,                                           //         ReportSize(16)
        0xB1, 0x02,                                           //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
        0xC0,                                                 //     EndCollection()
        0xC0,                                                 // EndCollection()
};

// \brief Prepare HID Report data to send.
// \param[in]   rtype   report type:
//                - HID_REPORT_INPUT           = input report requested
//                - HID_REPORT_FEATURE         = feature report requested
// \param[in]   req     request type:
//                - USBD_HID_REQ_EP_CTRL       = control endpoint request
//                - USBD_HID_REQ_PERIOD_UPDATE = idle period expiration request
//                - USBD_HID_REQ_EP_INT        = previously sent report on interrupt endpoint request
// \param[in]   rid     report ID (0 if only one report exists).
// \param[out]  buf     buffer containing report data to send.
// \return              number of report data bytes prepared to send or invalid report requested.
//              - value >= 0: number of report data bytes prepared to send
//              - value = -1: invalid report requested
int32_t USBD_HID0_GetReport(uint8_t rtype, uint8_t req, uint8_t rid, uint8_t *buf)
{

  switch (rtype)
  {
  case HID_REPORT_INPUT:
    if (req == USBD_HID_REQ_EP_INT) // Called after USBD_HID_GetReportTrigger to signal data obtained.
      return 0;

    return Fan_Control_Copy_RPM_To_Buffer(buf);

  case HID_REPORT_FEATURE:
    // The first byte of data is report ID
    buf[0] = rid;
    buf++;

    switch (rid)
    {
    case 1:
      return Fan_Control_Copy_Fan_Level_To_Buffer(buf);
    case 2:
      return Fan_Control_Copy_Internal_Temp_To_Buffer(buf);
    
    default:
      break;
    }
    

  default:
    break;
  }

  return -1;
}

// \brief Process received HID Report data.
// \param[in]   rtype   report type:
//                - HID_REPORT_OUTPUT    = output report received
//                - HID_REPORT_FEATURE   = feature report received
// \param[in]   req     request type:
//                - USBD_HID_REQ_EP_CTRL = report received on control endpoint
//                - USBD_HID_REQ_EP_INT  = report received on interrupt endpoint
// \param[in]   rid     report ID (0 if only one report exists).
// \param[in]   buf     buffer that receives report data.
// \param[in]   len     length of received report data.
// \return      true    received report data processed.
// \return      false   received report data not processed or request not supported.
bool USBD_HID0_SetReport(uint8_t rtype, uint8_t req, uint8_t rid, const uint8_t *buf, int32_t len)
{

  switch (rtype)
  {
  case HID_REPORT_OUTPUT:
    // return Fan_Control_Set_RPM_From_Host(buf, len);
    return true;

  case HID_REPORT_FEATURE:
    // The first byte of data is report ID
    len--;
    buf++;
    switch (rid)
    {
    case 1:
      return Fan_Control_Set_Fan_Level_From_Host(buf, len);
    
    default:
      break;
    }
    

  default:
    break;
  }

  return false;
}
